-- gpulist.lua
-- generated with gen_gpulist.rb at 2018-01-30 15:52:59 +0800
-- DO NOT EDIT!!!

return {

  {
    name = 'Apple A11 Bionic GPU',
    keywords = { 'A11', 'GPU',  },
    rank = 250,
    codename = '',
    arch = 'PowerVR Rogue',
    opengl = '',
    days = 131,
    score = 112489.0,
  },

  {
    name = 'Apple A10X Fusion GPU / PowerVR',
    keywords = { 'A10X', 'GPU',  },
    rank = 251,
    codename = '',
    arch = 'PowerVR Rogue',
    opengl = '',
    days = 228,
    score = 110560.0,
  },

  {
    name = 'Apple A9X / PowerVR Series 7XT',
    keywords = { 'A9X', 'Series', '7XT',  },
    rank = 286,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '4.3 OpenGL ES 3.x',
    days = 865,
    score = 50604.0,
  },

  {
    name = 'NVIDIA Tegra X1 Maxwell GPU',
    keywords = { 'Tegra', 'X1', 'Maxwell', 'GPU',  },
    rank = 309,
    codename = 'Erista',
    arch = 'Maxwell',
    opengl = '4.5',
    days = 1112,
    score = 57697.0,
  },

  {
    name = 'Apple A10 Fusion GPU / PowerVR',
    keywords = { 'A10', 'GPU',  },
    rank = 395,
    codename = '',
    arch = 'PowerVR Rogue',
    opengl = '',
    days = 500,
    score = 63680.0,
  },

  {
    name = 'Qualcomm Adreno 540',
    keywords = { 'Adreno', '540',  },
    rank = 411,
    codename = '',
    arch = '',
    opengl = 'ES 3.2',
    days = 305,
    score = 55378.0,
  },

  {
    name = 'ARM Mali-G71 MP20',
    keywords = { 'Mali', 'G71', 'MP20',  },
    rank = 412,
    codename = 'Mimir',
    arch = 'Bifrost',
    opengl = '',
    days = 298,
    score = 36347.0,
  },

  {
    name = 'ARM Mali-G72 MP12',
    keywords = { 'Mali', 'G72', 'MP12',  },
    rank = 413,
    codename = '',
    arch = 'Bifrost',
    opengl = '',
    days = 95,
    score = 35119.5,
  },

  {
    name = 'ARM Mali-G71 MP8',
    keywords = { 'Mali', 'G71', 'MP8',  },
    rank = 414,
    codename = 'Mimir',
    arch = 'Bifrost',
    opengl = '',
    days = 597,
    score = 35626.0,
  },

  {
    name = 'Qualcomm Adreno 530',
    keywords = { 'Adreno', '530',  },
    rank = 451,
    codename = '',
    arch = '',
    opengl = 'ES 3.1 AEP',
    days = 768,
    score = 32997.0,
  },

  {
    name = 'PowerVR GXA6850',
    keywords = { 'GXA6850',  },
    rank = 452,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '3.x, 4.x, OpenGL ES 3.0',
    days = 1230,
    score = 0.0,
  },

  {
    name = 'NVIDIA Tegra K1 Kepler GPU',
    keywords = { 'Tegra', 'K1', 'Kepler', 'GPU',  },
    rank = 453,
    codename = 'Logan / NVEA / GK20A',
    arch = 'Kepler',
    opengl = '4.4',
    days = 1476,
    score = 37318.5,
  },

  {
    name = 'Apple A9 / PowerVR GT7600',
    keywords = { 'GT7600',  },
    rank = 454,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '4.3 OpenGL ES 3.x',
    days = 865,
    score = 43372.5,
  },

  {
    name = 'ARM Mali-T880 MP12',
    keywords = { 'Mali', 'T880', 'MP12',  },
    rank = 455,
    codename = 'Midgard (4th Generation)',
    arch = 'Midgard (4rd-gen)',
    opengl = 'ES 3.1',
    days = 697,
    score = 33031.0,
  },

  {
    name = 'ARM Mali-T760 MP8',
    keywords = { 'Mali', 'T760', 'MP8',  },
    rank = 500,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1057,
    score = 26964.0,
  },

  {
    name = 'ARM Mali-G71 MP2',
    keywords = { 'Mali', 'G71', 'MP2',  },
    rank = 501,
    codename = 'Mimir',
    arch = 'Bifrost',
    opengl = '',
    days = 597,
    score = nil,
  },

  {
    name = 'Qualcomm Adreno 430',
    keywords = { 'Adreno', '430',  },
    rank = 506,
    codename = '',
    arch = '',
    opengl = 'ES 3.1',
    days = 1385,
    score = 36316.0,
  },

  {
    name = 'ARM Mali-T880 MP4',
    keywords = { 'Mali', 'T880', 'MP4',  },
    rank = 525,
    codename = 'Midgard (4th Generation)',
    arch = 'Midgard (4rd-gen)',
    opengl = 'ES 3.1',
    days = 787,
    score = 21577.0,
  },

  {
    name = 'ARM Mali-T760 MP6',
    keywords = { 'Mali', 'T760', 'MP6',  },
    rank = 557,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1573,
    score = 20244.0,
  },

  {
    name = 'ARM Mali-T880 MP2',
    keywords = { 'Mali', 'T880', 'MP2',  },
    rank = 558,
    codename = 'Midgard (4th Generation)',
    arch = 'Midgard (4rd-gen)',
    opengl = 'ES 3.1',
    days = 787,
    score = 14001.0,
  },

  {
    name = 'PowerVR GX6450',
    keywords = { 'GX6450',  },
    rank = 568,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '3.x, 4.x, OpenGL ES 3.0',
    days = 1230,
    score = 23937.0,
  },

  {
    name = 'Qualcomm Adreno 420',
    keywords = { 'Adreno', '420',  },
    rank = 569,
    codename = '',
    arch = '',
    opengl = 'ES 3.1',
    days = 1308,
    score = 20733.0,
  },

  {
    name = 'Qualcomm Adreno 418',
    keywords = { 'Adreno', '418',  },
    rank = 589,
    codename = '',
    arch = '',
    opengl = 'ES 3.1',
    days = 1308,
    score = 23298.5,
  },

  {
    name = 'Intel HD Graphics (Cherry Trail)',
    keywords = { 'HD', 'Graphics', 'Cherry', 'Trail',  },
    rank = 591,
    codename = 'Cherry Trail',
    arch = 'Intel Gen8',
    opengl = '4.3',
    days = 1056,
    score = 19303.0,
  },

  {
    name = 'Qualcomm Adreno 510',
    keywords = { 'Adreno', '510',  },
    rank = 666,
    codename = '',
    arch = 'Adreno 500',
    opengl = 'ES 3.2, Vulkan',
    days = 768,
    score = 21398.0,
  },

  {
    name = 'Qualcomm Adreno 330',
    keywords = { 'Adreno', '330',  },
    rank = 667,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 1840,
    score = 18007.0,
  },

  {
    name = 'PowerVR G6430',
    keywords = { 'G6430',  },
    rank = 668,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '3.x, 4.x, OpenGL ES 3.0',
    days = 1594,
    score = 18258.0,
  },

  {
    name = 'PowerVR GX6250',
    keywords = { 'GX6250',  },
    rank = 669,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '3.x, 4.x, OpenGL ES 3.x',
    days = 1230,
    score = 13446.0,
  },

  {
    name = 'PowerVR G6400',
    keywords = { 'G6400',  },
    rank = 670,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '3.x, 4.x, OpenGL ES 3.1',
    days = 1594,
    score = 0.0,
  },

  {
    name = 'Intel HD Graphics (Bay Trail)',
    keywords = { 'HD', 'Graphics', 'Bay', 'Trail',  },
    rank = 671,
    codename = 'Bay Trail',
    arch = 'Ivy Bridge',
    opengl = '4.0, ES 3.0',
    days = 1593,
    score = 14748.5,
  },

  {
    name = 'ARM Mali-T628 MP6',
    keywords = { 'Mali', 'T628', 'MP6',  },
    rank = 672,
    codename = 'Midgard (2nd Generation)',
    arch = '',
    opengl = 'ES 3.0',
    days = 1579,
    score = 13791.0,
  },

  {
    name = 'ARM Mali-T760 MP4',
    keywords = { 'Mali', 'T760', 'MP4',  },
    rank = 673,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1573,
    score = 0.0,
  },

  {
    name = 'PowerVR SGX554MP4',
    keywords = { 'SGX554MP4',  },
    rank = 711,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = 'ES 2.0',
    days = 1916,
    score = 0.0,
  },

  {
    name = 'ARM Mali-T628 MP4',
    keywords = { 'Mali', 'T628', 'MP4',  },
    rank = 712,
    codename = 'Midgard (2nd Generation)',
    arch = '',
    opengl = 'ES 3.0',
    days = 1235,
    score = 11984.0,
  },

  {
    name = 'Qualcomm Adreno 508',
    keywords = { 'Adreno', '508',  },
    rank = 713,
    codename = '',
    arch = 'Adreno 500',
    opengl = 'ES 3.2, Vulkan',
    days = 258,
    score = 18386.0,
  },

  {
    name = 'Qualcomm Adreno 506',
    keywords = { 'Adreno', '506',  },
    rank = 714,
    codename = '',
    arch = 'Adreno 500',
    opengl = 'ES 3.2, Vulkan',
    days = 768,
    score = 13303.5,
  },

  {
    name = 'Qualcomm Adreno 505',
    keywords = { 'Adreno', '505',  },
    rank = 715,
    codename = '',
    arch = 'Adreno 500',
    opengl = 'ES 3.2, Vulkan',
    days = 768,
    score = 9691.0,
  },

  {
    name = 'ARM Mali-T860 MP2',
    keywords = { 'Mali', 'T860', 'MP2',  },
    rank = 719,
    codename = 'Midgard',
    arch = 'Midgard',
    opengl = 'ES 3.1 AEP',
    days = 1116,
    score = 10361.0,
  },

  {
    name = 'ARM Mali-T830 MP3',
    keywords = { 'Mali', 'T830', 'MP3',  },
    rank = 720,
    codename = '',
    arch = '',
    opengl = 'ES 3.2',
    days = 660,
    score = 0.0,
  },

  {
    name = 'ARM Mali-T604 MP4',
    keywords = { 'Mali', 'T604', 'MP4',  },
    rank = 726,
    codename = 'Midgard',
    arch = '',
    opengl = 'ES 3.0',
    days = 1896,
    score = nil,
  },

  {
    name = 'NVIDIA GeForce Tegra 4',
    keywords = { 'GeForce', 'Tegra', '4',  },
    rank = 731,
    codename = 'Tegra 3',
    arch = '',
    opengl = '',
    days = 40,
    score = nil,
  },

  {
    name = 'PowerVR G6200',
    keywords = { 'G6200',  },
    rank = 732,
    codename = 'Rogue',
    arch = 'PowerVR Rogue',
    opengl = '3.x, 4.x, OpenGL ES 3.1',
    days = 1594,
    score = 10862.0,
  },

  {
    name = 'Qualcomm Adreno 405',
    keywords = { 'Adreno', '405',  },
    rank = 733,
    codename = '',
    arch = '',
    opengl = 'ES 3.1',
    days = 1427,
    score = 8161.0,
  },

  {
    name = 'ARM Mali-T830 MP2',
    keywords = { 'Mali', 'T830', 'MP2',  },
    rank = 734,
    codename = '',
    arch = '',
    opengl = 'ES 3.2',
    days = 660,
    score = 10603.0,
  },

  {
    name = 'PowerVR SGX543MP4',
    keywords = { 'SGX543MP4',  },
    rank = 761,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = 'ES 2.0',
    days = 3233,
    score = nil,
  },

  {
    name = 'ARM Mali-T624',
    keywords = { 'Mali', 'T624',  },
    rank = 762,
    codename = '',
    arch = 'Midgard 2nd Gen',
    opengl = 'ES 3.0',
    days = 1628,
    score = 0.0,
  },

  {
    name = 'Qualcomm Adreno 320',
    keywords = { 'Adreno', '320',  },
    rank = 763,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 2155,
    score = 10644.0,
  },

  {
    name = 'ARM Mali-T760 MP2',
    keywords = { 'Mali', 'T760', 'MP2',  },
    rank = 764,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1573,
    score = 7541.0,
  },

  {
    name = 'ARM Mali-T720 MP4',
    keywords = { 'Mali', 'T720', 'MP4',  },
    rank = 765,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1544,
    score = 6250.0,
  },

  {
    name = 'ARM Mali-450 MP4',
    keywords = { 'Mali', '450', 'MP4',  },
    rank = 766,
    codename = '',
    arch = 'Utgard',
    opengl = '',
    days = 28,
    score = nil,
  },

  {
    name = 'ARM Mali-T830 MP1',
    keywords = { 'Mali', 'T830', 'MP1',  },
    rank = 767,
    codename = '',
    arch = '',
    opengl = 'ES 3.2',
    days = 660,
    score = 7470.0,
  },

  {
    name = 'PowerVR SGX543MP3',
    keywords = { 'SGX543MP3',  },
    rank = 775,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = 'ES 2.0',
    days = 3233,
    score = nil,
  },

  {
    name = 'PowerVR SGX543MP2',
    keywords = { 'SGX543MP2',  },
    rank = 785,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = 'ES 2.0',
    days = 3233,
    score = nil,
  },

  {
    name = 'PowerVR SGX545',
    keywords = { 'SGX545',  },
    rank = 788,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '9_3/10.1',
    days = 32,
    score = nil,
  },

  {
    name = 'PowerVR SGX544MP2',
    keywords = { 'SGX544MP2',  },
    rank = 789,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '9_3/10.1',
    days = 45,
    score = nil,
  },

  {
    name = 'ARM Mali-T720 MP2',
    keywords = { 'Mali', 'T720', 'MP2',  },
    rank = 790,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1057,
    score = 4415.0,
  },

  {
    name = 'PowerVR SGX544',
    keywords = { 'SGX544',  },
    rank = 791,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '9_3/10.1',
    days = 45,
    score = nil,
  },

  {
    name = 'Qualcomm Adreno 308',
    keywords = { 'Adreno', '308',  },
    rank = 792,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 710,
    score = 5461.5,
  },

  {
    name = 'Qualcomm Adreno 306',
    keywords = { 'Adreno', '306',  },
    rank = 793,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 1968,
    score = 3838.0,
  },

  {
    name = 'Qualcomm Adreno 305',
    keywords = { 'Adreno', '305',  },
    rank = 794,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 1968,
    score = 4210.0,
  },

  {
    name = 'Qualcomm Adreno 304',
    keywords = { 'Adreno', '304',  },
    rank = 795,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 935,
    score = 3998.0,
  },

  {
    name = 'ARM Mali-T720',
    keywords = { 'Mali', 'T720',  },
    rank = 796,
    codename = 'Midgard (3rd Generation)',
    arch = 'Midgard (3rd-gen)',
    opengl = 'ES 3.1',
    days = 1057,
    score = 2912.5,
  },

  {
    name = 'Vivante GC7000UL',
    keywords = { 'GC7000UL',  },
    rank = 797,
    codename = '',
    arch = '',
    opengl = 'ES 3.1',
    days = 1481,
    score = 0.0,
  },

  {
    name = 'Qualcomm Adreno 302',
    keywords = { 'Adreno', '302',  },
    rank = 798,
    codename = '',
    arch = '',
    opengl = 'ES 3.0',
    days = 1676,
    score = 3592.0,
  },

  {
    name = 'Qualcomm Adreno 225',
    keywords = { 'Adreno', '225',  },
    rank = 806,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 2155,
    score = 0.0,
  },

  {
    name = 'Vivante GC4000',
    keywords = { 'GC4000',  },
    rank = 807,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 1726,
    score = nil,
  },

  {
    name = 'ARM Mali-400 MP4',
    keywords = { 'Mali', '400', 'MP4',  },
    rank = 808,
    codename = '',
    arch = 'Utgard',
    opengl = '',
    days = 0,
    score = nil,
  },

  {
    name = 'NVIDIA GeForce ULP (Tegra 3)',
    keywords = { 'GeForce', 'ULP', 'Tegra', '3',  },
    rank = 809,
    codename = 'Tegra 3',
    arch = '',
    opengl = '',
    days = 40,
    score = nil,
  },

  {
    name = 'Broadcom VideoCore-IV',
    keywords = { 'VideoCore', 'IV',  },
    rank = 810,
    codename = '',
    arch = '',
    opengl = '',
    days = 40,
    score = nil,
  },

  {
    name = 'Qualcomm Adreno 220',
    keywords = { 'Adreno', '220',  },
    rank = 811,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 2791,
    score = nil,
  },

  {
    name = 'Vivante GC1000+ Dual-Core',
    keywords = { 'GC1000+', 'Dual', 'Core',  },
    rank = 812,
    codename = '',
    arch = '',
    opengl = '2.1 / ES 2.0',
    days = 1592,
    score = 2373.0,
  },

  {
    name = 'ARM Mali-400 MP2',
    keywords = { 'Mali', '400', 'MP2',  },
    rank = 813,
    codename = '',
    arch = 'Utgard',
    opengl = '',
    days = 0,
    score = nil,
  },

  {
    name = 'ARM Mali-400 MP',
    keywords = { 'Mali', '400', 'MP',  },
    rank = 814,
    codename = '',
    arch = 'Utgard',
    opengl = '',
    days = 0,
    score = nil,
  },

  {
    name = 'NVIDIA GeForce ULP (Tegra 2)',
    keywords = { 'GeForce', 'ULP', 'Tegra', '2',  },
    rank = 815,
    codename = 'Tegra 2',
    arch = '',
    opengl = '',
    days = 40,
    score = nil,
  },

  {
    name = 'PowerVR SGX540',
    keywords = { 'SGX540',  },
    rank = 817,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '',
    days = 45,
    score = nil,
  },

  {
    name = 'Qualcomm Adreno 205',
    keywords = { 'Adreno', '205',  },
    rank = 819,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 2694,
    score = nil,
  },

  {
    name = 'Qualcomm Adreno 203',
    keywords = { 'Adreno', '203',  },
    rank = 820,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 1943,
    score = 0.0,
  },

  {
    name = 'Vivante GC800',
    keywords = { 'GC800',  },
    rank = 821,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 2212,
    score = nil,
  },

  {
    name = 'PowerVR SGX535',
    keywords = { 'SGX535',  },
    rank = 822,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '9.0c',
    days = 45,
    score = nil,
  },

  {
    name = 'PowerVR SGX531',
    keywords = { 'SGX531',  },
    rank = 823,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '',
    days = 0,
    score = nil,
  },

  {
    name = 'PowerVR SGX530',
    keywords = { 'SGX530',  },
    rank = 824,
    codename = '',
    arch = 'PowerVR SGX5',
    opengl = '',
    days = 0,
    score = nil,
  },

  {
    name = 'Qualcomm Adreno 200',
    keywords = { 'Adreno', '200',  },
    rank = 825,
    codename = '',
    arch = '',
    opengl = 'ES 2.0',
    days = 3399,
    score = nil,
  },

  {
    name = 'ARM Mali-200',
    keywords = { 'Mali', '200',  },
    rank = 826,
    codename = '',
    arch = 'Utgard',
    opengl = '',
    days = 65,
    score = nil,
  },

  {
    name = 'Vivante GC2000',
    keywords = { 'GC2000',  },
    rank = 9999,
    codename = '',
    arch = '',
    opengl = '',
    days = 9999,
    score = nil,
  },

  {
    name = 'Emulated GPU running OpenGL ES 2.0',
    keywords = { 'Emulated', 'GPU', 'running', 'OpenGL', 'ES', '2.0',  },
    rank = 100,
    codename = '',
    arch = '',
    opengl = '',
    days = 9999,
    score = 150000,
  },

}
